=== antoniogiroz/Recio_Vega_Inma_Git_Coop/EuroJackpot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="EuroJackpot">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Apuesta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Apuesta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Numeros"/>
        <xs:element ref="Soles"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Numeros">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="5" maxOccurs="5" name="Numero" type="NumerosApuesta" />
      </xs:sequence>
    </xs:complexType>
    <xs:key name="NumeroUnico">
      <xs:selector xpath="Numero" />
      <xs:field xpath="." />
    </xs:key>
  </xs:element>
  <xs:element name="Soles">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="2" maxOccurs="2" name="Numero" type="NumerosSoles"/>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="SolUnico">
      <xs:selector xpath="Numero" />
      <xs:field xpath="." />
    </xs:key>
  </xs:element>
  <xs:simpleType name="NumerosApuesta">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="50"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NumerosSoles">
    <xs:restriction base="xs:positiveInteger">
      <xs:minExclusive value="1"/>
      <xs:maxExclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== antoniogiroz/Recio_Vega_Inma_Git_Coop/EuroJackpot.xml
<?xml version="1.0" encoding="UTF-8"?>
<EuroJackpot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="EuroJackpot.xsd">
    <Apuesta>
        <Numeros>
            <Numero>23</Numero>
            <Numero>1</Numero>
            <Numero>12</Numero>
            <Numero>38</Numero>
            <Numero>19</Numero>
        </Numeros>
        <Soles>
            <Numero>2</Numero>
            <Numero>9</Numero>
        </Soles>
    </Apuesta>
</EuroJackpot>
